# Generated by Django 4.2 on 2024-11-12 12:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LocationMedia",
        ),
    ]
