# Generated by Django 5.1.3 on 2024-11-05 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="memorymap",
            name="instagram_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="memorymap",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="memorymap",
            name="location_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="memorymap",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="memorynode",
            name="media_type",
            field=models.CharField(
                choices=[
                    ("image", "Image"),
                    ("video", "Video"),
                    ("instagram", "Instagram"),
                ],
                default="image",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="memorynode",
            name="media_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="memorymap",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="memorynode",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name="InstagramReel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("description", models.TextField(blank=True)),
                ("likes", models.IntegerField(default=0)),
                ("comments", models.IntegerField(default=0)),
                ("date_posted", models.DateTimeField()),
                ("date_extracted", models.DateTimeField(auto_now_add=True)),
                (
                    "memory_map",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reels",
                        to="core.memorymap",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "extracted_from",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="extracted_locations",
                        to="core.instagramreel",
                    ),
                ),
                (
                    "memory_map",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="core.memorymap",
                    ),
                ),
            ],
        ),
    ]
