# Generated by Django 4.2 on 2024-11-14 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_delete_locationmedia"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserLocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("custom_name", models.CharField(blank=True, max_length=255)),
                ("custom_description", models.TextField(blank=True)),
                ("custom_category", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("is_favorite", models.BooleanField(default=False)),
                ("notify_enabled", models.BooleanField(default=False)),
                ("notify_radius", models.FloatField(default=1.0)),
                (
                    "sync_status",
                    models.IntegerField(
                        choices=[(0, "Not Synced"), (1, "Syncing"), (2, "Synced")],
                        default=0,
                    ),
                ),
                ("last_synced", models.DateTimeField(blank=True, null=True)),
                (
                    "firebase_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("saved_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-saved_at"],
            },
        ),
        migrations.RemoveIndex(
            model_name="location",
            name="core_locati_created_101beb_idx",
        ),
        migrations.RemoveField(
            model_name="location",
            name="comments",
        ),
        migrations.RemoveField(
            model_name="location",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="location",
            name="date_extracted",
        ),
        migrations.RemoveField(
            model_name="location",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="location",
            name="likes",
        ),
        migrations.RemoveField(
            model_name="location",
            name="tags",
        ),
        migrations.AddField(
            model_name="location",
            name="firebase_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="is_instagram_source",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="location",
            name="last_synced",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="sync_status",
            field=models.IntegerField(
                choices=[(0, "Not Synced"), (1, "Syncing"), (2, "Synced")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="category",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="location",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["sync_status"], name="core_locati_sync_st_297716_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["is_instagram_source"], name="core_locati_is_inst_2a9e9c_idx"
            ),
        ),
        migrations.AddField(
            model_name="userlocation",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_by",
                to="core.location",
            ),
        ),
        migrations.AddField(
            model_name="userlocation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_locations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="userlocation",
            index=models.Index(
                fields=["user", "sync_status"], name="core_userlo_user_id_d662cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userlocation",
            index=models.Index(
                fields=["location", "is_favorite"],
                name="core_userlo_locatio_32028a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userlocation",
            index=models.Index(
                fields=["notify_enabled"], name="core_userlo_notify__a08c64_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userlocation",
            unique_together={("user", "location")},
        ),
    ]
