# Generated by Django 4.2 on 2024-11-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_userlocation_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="location",
            name="core_locati_is_inst_2a9e9c_idx",
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["location_type"], name="core_locati_locatio_1406db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["is_instagram_source", "instagram_url"],
                name="core_locati_is_inst_d32d6c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["firebase_id"], name="core_locati_firebas_0bf8a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["-created_at"], name="core_locati_created_367075_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userlocation",
            index=models.Index(
                fields=["user", "saved_at"], name="core_userlo_user_id_20ee9e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userlocation",
            index=models.Index(
                fields=["sync_status"], name="core_userlo_sync_st_e7a6bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userlocation",
            index=models.Index(
                fields=["-saved_at"], name="core_userlo_saved_a_6d3d2f_idx"
            ),
        ),
    ]
