# Generated by Django 5.2.17 on 2026-09-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_location_core_locati_is_inst_2a9e9c_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="location",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="location",
            name="version",
            field=models.IntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["version"], name="core_locati_version_c29685_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["is_deleted", "sync_status"],
                name="core_locati_is_dele_1291d0_idx",
            ),
        ),
    ]
