# Generated by Django 5.2.17 on 2026-09-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_location_is_deleted_location_last_modified_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstagramReelCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("locations", models.JSONField(blank=True, default=list)),
                ("date_posted", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("analyzed", "Analyzed"),
                            ("no_locations", "No Locations Found"),
                            ("failed", "Failed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("failure_reason", models.TextField(blank=True)),
                ("analyzed_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-analyzed_at"],
                "indexes": [
                    models.Index(fields=["url"], name="core_instag_url_7b4ced_idx"),
                    models.Index(
                        fields=["status"], name="core_instag_status_a05661_idx"
                    ),
                ],
            },
        ),
        migrations.DeleteModel(
            name="InstagramReel",
        ),
    ]
