# Generated by Django 5.2.17 on 2026-09-26 03:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

LEGACY_CATEGORY_MAP = {
    'food': 'food', 'restaurant': 'food', 'bakery': 'food', 'street food': 'food',
    'cafe': 'cafe', 'café': 'cafe', 'coffee': 'cafe', 'dessert': 'cafe',
    'bar': 'bar', 'nightlife': 'bar', 'pub': 'bar',
    'nature': 'nature', 'park': 'nature', 'hiking': 'nature', 'mountain': 'nature',
    'beach': 'beach',
    'viewpoint': 'viewpoint', 'view': 'viewpoint',
    'landmark': 'landmark', 'monument': 'landmark', 'historic': 'landmark', 'temple': 'landmark',
    'museum': 'culture', 'culture': 'culture', 'art': 'culture', 'gallery': 'culture',
    'shopping': 'shopping', 'shop': 'shopping', 'market': 'shopping',
    'hotel': 'stay', 'stay': 'stay', 'accommodation': 'stay',
    'activity': 'activity', 'entertainment': 'activity',
}


def copy_saves_to_saved_locations(apps, schema_editor):
    """One SavedLocation per old UserLocation, flattening in its (possibly
    shared) Location and applying the user's custom overrides."""
    UserLocation = apps.get_model('core', 'UserLocation')
    SavedLocation = apps.get_model('core', 'SavedLocation')
    for old in UserLocation.objects.select_related('location').iterator():
        place = old.location
        raw_category = (old.custom_category or place.category or '').strip().lower()
        saved = SavedLocation.objects.create(
            id=old.id,
            user_id=old.user_id,
            name=(old.custom_name or place.name or 'Saved place')[:255],
            description=old.custom_description or place.description or '',
            notes=old.notes or '',
            category=LEGACY_CATEGORY_MAP.get(raw_category, 'other'),
            latitude=place.latitude,
            longitude=place.longitude,
            address=(place.address or '')[:500],
            source='instagram' if place.is_instagram_source or place.instagram_url else 'manual',
            instagram_url=place.instagram_url or '',
            is_favorite=old.is_favorite,
            notify_enabled=old.notify_enabled,
            notify_radius_km=min(max(old.notify_radius or 1.0, 0.1), 50),
        )
        SavedLocation.objects.filter(pk=saved.pk).update(created_at=old.saved_at)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_instagramreelcache_delete_instagramreel"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedLocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("food", "Food"),
                            ("cafe", "Café"),
                            ("bar", "Bars & Nightlife"),
                            ("nature", "Nature"),
                            ("beach", "Beach"),
                            ("viewpoint", "Viewpoint"),
                            ("landmark", "Landmark"),
                            ("culture", "Culture"),
                            ("shopping", "Shopping"),
                            ("stay", "Stay"),
                            ("activity", "Activity"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ]
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ]
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=500)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Added manually"),
                            ("instagram", "From an Instagram reel"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("instagram_url", models.URLField(blank=True, max_length=500)),
                ("is_favorite", models.BooleanField(default=False)),
                ("visited", models.BooleanField(default=False)),
                ("notify_enabled", models.BooleanField(default=False)),
                (
                    "notify_radius_km",
                    models.FloatField(
                        default=1.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.1),
                            django.core.validators.MaxValueValidator(50),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="savedlocation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_locations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="savedlocation",
            index=models.Index(
                fields=["user", "-created_at"], name="core_savedl_user_id_c9bf7a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="savedlocation",
            index=models.Index(
                fields=["user", "category"], name="core_savedl_user_id_440cc5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="savedlocation",
            index=models.Index(
                fields=["user", "is_favorite"], name="core_savedl_user_id_5d292e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="savedlocation",
            index=models.Index(
                fields=["user", "instagram_url"], name="core_savedl_user_id_4e5d38_idx"
            ),
        ),
        migrations.RunPython(copy_saves_to_saved_locations, migrations.RunPython.noop),
        migrations.RemoveIndex(
            model_name="instagramreelcache",
            name="core_instag_url_7b4ced_idx",
        ),
        migrations.RemoveIndex(
            model_name="instagramreelcache",
            name="core_instag_status_a05661_idx",
        ),
        migrations.AlterField(
            model_name="instagramreelcache",
            name="url",
            field=models.URLField(max_length=500, unique=True),
        ),
        migrations.DeleteModel(
            name="UserLocation",
        ),
        migrations.DeleteModel(
            name="Location",
        ),
    ]
