# Generated by Django 5.2.17 on 2026-09-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="last_sync",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="notification_settings",
            field=models.JSONField(default=dict),
        ),
    ]
