# Generated by Django 5.2.17 on 2026-09-26 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userprofile_last_sync_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
